// <auto-generated />
using ClinicAPI.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClinicAPI.Migrations
{
    [DbContext(typeof(ClinicContext))]
    [Migration("20240514153658_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ClinicAPI.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Experience")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Speciality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            Experience = 5,
                            Name = "Shrish",
                            Speciality = "ENT"
                        },
                        new
                        {
                            Id = 101,
                            Experience = 5,
                            Name = "Naresh",
                            Speciality = "ENT"
                        },
                        new
                        {
                            Id = 102,
                            Experience = 5,
                            Name = "Raghul",
                            Speciality = "Heart"
                        },
                        new
                        {
                            Id = 103,
                            Experience = 5,
                            Name = "Revs",
                            Speciality = "Heart"
                        },
                        new
                        {
                            Id = 104,
                            Experience = 5,
                            Name = "Raks",
                            Speciality = "Bone"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
